// =====================================================================
// data-livros.mjs — os 66 livros da Bíblia protestante, com divisão
// canônica, número de capítulos e resumo editorial original.
// =====================================================================

export const GRUPOS = [
  { id: 'pentateuco', nome: 'Pentateuco (Lei)', testamento: 'AT' },
  { id: 'historicos-at', nome: 'Históricos', testamento: 'AT' },
  { id: 'poeticos', nome: 'Poéticos e Sapienciais', testamento: 'AT' },
  { id: 'profetas-maiores', nome: 'Profetas Maiores', testamento: 'AT' },
  { id: 'profetas-menores', nome: 'Profetas Menores', testamento: 'AT' },
  { id: 'evangelhos', nome: 'Evangelhos', testamento: 'NT' },
  { id: 'historico-nt', nome: 'História da Igreja', testamento: 'NT' },
  { id: 'cartas-paulo', nome: 'Cartas de Paulo', testamento: 'NT' },
  { id: 'cartas-gerais', nome: 'Cartas Gerais', testamento: 'NT' },
  { id: 'profetico-nt', nome: 'Profecia', testamento: 'NT' },
];

export const LIVROS = [
  // ---------- ANTIGO TESTAMENTO ----------
  { nome: 'Gênesis', grupo: 'pentateuco', capitulos: 50, resumo: 'O livro dos começos: a criação do mundo, a queda, o dilúvio e a família de Abraão, por quem Deus promete abençoar todas as nações.' },
  { nome: 'Êxodo', grupo: 'pentateuco', capitulos: 40, resumo: 'Deus liberta Israel da escravidão no Egito pelas mãos de Moisés, entrega os Dez Mandamentos no Sinai e passa a habitar no tabernáculo.' },
  { nome: 'Levítico', grupo: 'pentateuco', capitulos: 27, resumo: 'O manual do culto e da santidade: sacrifícios, festas e leis que ensinavam Israel a viver diante de um Deus santo — "sede santos, porque eu sou santo".' },
  { nome: 'Números', grupo: 'pentateuco', capitulos: 36, resumo: 'Quarenta anos de deserto entre o Sinai e a terra prometida: censos, murmurações e a fidelidade de Deus a uma geração infiel.' },
  { nome: 'Deuteronômio', grupo: 'pentateuco', capitulos: 34, resumo: 'Os discursos de despedida de Moisés: a lei repetida para a nova geração e o apelo central — "amarás o Senhor, teu Deus, de todo o teu coração".' },
  { nome: 'Josué', grupo: 'historicos-at', capitulos: 24, resumo: 'A conquista da terra prometida: Jericó, as campanhas militares, a divisão da herança e o desafio final — "eu e a minha casa serviremos ao Senhor".' },
  { nome: 'Juízes', grupo: 'historicos-at', capitulos: 21, resumo: 'O ciclo de queda e resgate de Israel: pecado, opressão, clamor e libertação por juízes como Débora, Gideão e Sansão.' },
  { nome: 'Rute', grupo: 'historicos-at', capitulos: 4, resumo: 'Uma estrangeira leal, uma sogra amargurada e um resgatador generoso: a história de amor que colocou uma moabita na genealogia de Jesus.' },
  { nome: '1 Samuel', grupo: 'historicos-at', capitulos: 31, resumo: 'Do último juiz ao primeiro rei: Samuel, a ascensão e queda de Saul e a unção do jovem pastor Davi — incluindo o duelo com Golias.' },
  { nome: '2 Samuel', grupo: 'historicos-at', capitulos: 24, resumo: 'O reinado de Davi: as vitórias, a aliança eterna prometida por Deus, o pecado com Bate-Seba e as dolorosas consequências na família real.' },
  { nome: '1 Reis', grupo: 'historicos-at', capitulos: 22, resumo: 'A glória de Salomão e o templo, a divisão do reino em dois e o ministério de fogo do profeta Elias contra a idolatria de Acabe.' },
  { nome: '2 Reis', grupo: 'historicos-at', capitulos: 25, resumo: 'Eliseu e os profetas, a queda de Samaria diante da Assíria e a destruição de Jerusalém pela Babilônia: a colheita amarga da idolatria.' },
  { nome: '1 Crônicas', grupo: 'historicos-at', capitulos: 29, resumo: 'A história de Israel recontada para os que voltaram do exílio, com foco em Davi, na adoração e nas promessas que permaneciam de pé.' },
  { nome: '2 Crônicas', grupo: 'historicos-at', capitulos: 36, resumo: 'De Salomão ao exílio: os reis de Judá avaliados por um único critério — buscaram ou não ao Senhor — e a promessa de restauração.' },
  { nome: 'Esdras', grupo: 'historicos-at', capitulos: 10, resumo: 'O retorno do exílio babilônico: a reconstrução do templo e a reforma espiritual liderada pelo escriba que "preparou o coração para buscar a lei".' },
  { nome: 'Neemias', grupo: 'historicos-at', capitulos: 13, resumo: 'O copeiro do rei que reconstruiu os muros de Jerusalém em 52 dias: liderança, oração e trabalho — "a alegria do Senhor é a vossa força".' },
  { nome: 'Ester', grupo: 'historicos-at', capitulos: 10, resumo: 'A judia que se tornou rainha da Pérsia "para tal tempo como este" e salvou seu povo do extermínio — o livro onde Deus age sem ser nomeado.' },
  { nome: 'Jó', grupo: 'poeticos', capitulos: 42, resumo: 'O justo que perdeu tudo e o debate mais profundo da Bíblia sobre o sofrimento — encerrado não com respostas, mas com um encontro com Deus.' },
  { nome: 'Salmos', grupo: 'poeticos', capitulos: 150, resumo: 'O hinário e o livro de orações de Israel: 150 poemas de louvor, lamento, gratidão e esperança para cada estação da alma.' },
  { nome: 'Provérbios', grupo: 'poeticos', capitulos: 31, resumo: 'A sabedoria prática de Salomão para o dia a dia: palavras, dinheiro, trabalho e relacionamentos — começando pelo temor do Senhor.' },
  { nome: 'Eclesiastes', grupo: 'poeticos', capitulos: 12, resumo: 'A investigação do Pregador sobre o sentido da vida "debaixo do sol": tudo é vaidade, até que Deus entre na equação.' },
  { nome: 'Cantares', grupo: 'poeticos', capitulos: 8, resumo: 'O Cântico dos Cânticos: a celebração poética do amor entre o amado e a amada — "as muitas águas não podem apagar este amor".' },
  { nome: 'Isaías', grupo: 'profetas-maiores', capitulos: 66, resumo: 'O "evangelho do Antigo Testamento": juízo e consolo, o Emanuel, o Servo Sofredor do capítulo 53 e novos céus e nova terra.' },
  { nome: 'Jeremias', grupo: 'profetas-maiores', capitulos: 52, resumo: 'O profeta que chorou: quarenta anos anunciando a queda de Jerusalém e, no meio das lágrimas, a promessa da nova aliança.' },
  { nome: 'Lamentações', grupo: 'profetas-maiores', capitulos: 5, resumo: 'Cinco poemas fúnebres sobre as ruínas de Jerusalém — e, no centro exato, a chama que não se apaga: "as suas misericórdias se renovam a cada manhã".' },
  { nome: 'Ezequiel', grupo: 'profetas-maiores', capitulos: 48, resumo: 'Visões impressionantes no exílio: a glória de Deus que parte e retorna, o vale de ossos secos e a promessa de um coração novo.' },
  { nome: 'Daniel', grupo: 'profetas-maiores', capitulos: 12, resumo: 'Fidelidade na Babilônia: a cova dos leões, a fornalha ardente e as visões proféticas dos impérios e do Reino eterno de Deus.' },
  { nome: 'Oseias', grupo: 'profetas-menores', capitulos: 14, resumo: 'O casamento do profeta com uma mulher infiel como retrato vivo do amor de Deus por um povo adúltero — e da disposição de resgatá-lo.' },
  { nome: 'Joel', grupo: 'profetas-menores', capitulos: 3, resumo: 'De uma praga de gafanhotos ao Dia do Senhor: o chamado ao arrependimento e a promessa — "derramarei o meu Espírito sobre toda a carne".' },
  { nome: 'Amós', grupo: 'profetas-menores', capitulos: 9, resumo: 'O boiadeiro que rugiu contra a injustiça social: religião sem retidão é insuportável a Deus — "corra o juízo como as águas".' },
  { nome: 'Obadias', grupo: 'profetas-menores', capitulos: 1, resumo: 'O livro mais curto do Antigo Testamento: o juízo sobre Edom, que se alegrou com a queda do irmão Israel.' },
  { nome: 'Jonas', grupo: 'profetas-menores', capitulos: 4, resumo: 'O profeta que fugiu de Deus, orou do ventre do grande peixe e viu Nínive inteira se arrepender — para seu próprio desgosto.' },
  { nome: 'Miqueias', grupo: 'profetas-menores', capitulos: 7, resumo: 'Juízo e esperança para Judá, a profecia do Messias nascido em Belém e o resumo da vida com Deus: praticar a justiça, amar a beneficência e andar humildemente.' },
  { nome: 'Naum', grupo: 'profetas-menores', capitulos: 3, resumo: 'A queda de Nínive, capital do império mais cruel da época: Deus é refúgio para os seus, mas não deixa o mal impune.' },
  { nome: 'Habacuque', grupo: 'profetas-menores', capitulos: 3, resumo: 'O profeta que questionou Deus — "até quando?" — e aprendeu a resposta que atravessou os séculos: "o justo, pela sua fé, viverá".' },
  { nome: 'Sofonias', grupo: 'profetas-menores', capitulos: 3, resumo: 'O grande Dia do Senhor se aproxima: juízo sobre as nações e, no final, o Deus que "se alegra sobre ti com cântico".' },
  { nome: 'Ageu', grupo: 'profetas-menores', capitulos: 2, resumo: 'Quatro sermões diretos para um povo que morava em casas apaineladas enquanto o templo estava em ruínas: "considerai os vossos caminhos".' },
  { nome: 'Zacarias', grupo: 'profetas-menores', capitulos: 14, resumo: 'Visões noturnas de esperança para os que reconstruíam Jerusalém — e profecias messiânicas detalhadas: o rei humilde montado num jumentinho.' },
  { nome: 'Malaquias', grupo: 'profetas-menores', capitulos: 4, resumo: 'A última palavra do Antigo Testamento: um debate entre Deus e um povo cansado, os dízimos, e a promessa do mensageiro que prepararia o caminho.' },
  // ---------- NOVO TESTAMENTO ----------
  { nome: 'Mateus', grupo: 'evangelhos', capitulos: 28, resumo: 'Jesus, o Rei prometido: o evangelho que liga o Antigo Testamento ao Novo, com o Sermão do Monte e a Grande Comissão.' },
  { nome: 'Marcos', grupo: 'evangelhos', capitulos: 16, resumo: 'O evangelho da ação: curto, urgente e vívido — o Filho de Deus que "não veio para ser servido, mas para servir e dar a sua vida em resgate de muitos".' },
  { nome: 'Lucas', grupo: 'evangelhos', capitulos: 24, resumo: 'A investigação cuidadosa do médico Lucas: o Salvador dos excluídos, as parábolas do filho pródigo e do bom samaritano, o evangelho da misericórdia.' },
  { nome: 'João', grupo: 'evangelhos', capitulos: 21, resumo: 'O evangelho do amor e da fé: "o Verbo se fez carne", os sete "Eu sou" e o propósito declarado — "para que creiais que Jesus é o Cristo".' },
  { nome: 'Atos', grupo: 'historico-nt', capitulos: 28, resumo: 'O Espírito Santo em ação: o nascimento da igreja no Pentecostes, a conversão de Paulo e o evangelho indo de Jerusalém até os confins da terra.' },
  { nome: 'Romanos', grupo: 'cartas-paulo', capitulos: 16, resumo: 'A exposição mais completa do evangelho: todos pecaram, a justificação é pela fé, e nada "nos poderá separar do amor de Deus".' },
  { nome: '1 Coríntios', grupo: 'cartas-paulo', capitulos: 16, resumo: 'Paulo corrige uma igreja talentosa e problemática: divisões, imoralidade, dons espirituais — e o caminho mais excelente, o amor do capítulo 13.' },
  { nome: '2 Coríntios', grupo: 'cartas-paulo', capitulos: 13, resumo: 'A carta mais pessoal de Paulo: o tesouro em vasos de barro, o espinho na carne e a graça que se aperfeiçoa na fraqueza.' },
  { nome: 'Gálatas', grupo: 'cartas-paulo', capitulos: 6, resumo: 'A carta da liberdade cristã: salvação pela graça, não pelas obras da lei — "para a liberdade Cristo nos libertou" — e o fruto do Espírito.' },
  { nome: 'Efésios', grupo: 'cartas-paulo', capitulos: 6, resumo: 'As riquezas da igreja em Cristo: eleitos, adotados e salvos pela graça; a nova vida no lar e no trabalho; e toda a armadura de Deus.' },
  { nome: 'Filipenses', grupo: 'cartas-paulo', capitulos: 4, resumo: 'A carta da alegria, escrita da prisão: "alegrai-vos sempre no Senhor", o hino da humilhação de Cristo e o segredo do contentamento.' },
  { nome: 'Colossenses', grupo: 'cartas-paulo', capitulos: 4, resumo: 'A supremacia absoluta de Cristo: imagem do Deus invisível, criador e sustentador de tudo — e a vida nova enraizada nele.' },
  { nome: '1 Tessalonicenses', grupo: 'cartas-paulo', capitulos: 5, resumo: 'Esperança para uma igreja jovem e perseguida: a volta de Cristo, o consolo pelos que dormem e o chamado à santidade e à gratidão.' },
  { nome: '2 Tessalonicenses', grupo: 'cartas-paulo', capitulos: 3, resumo: 'Correções sobre o Dia do Senhor: firmeza na perseguição, verdade contra boatos e trabalho digno enquanto se espera a volta de Cristo.' },
  { nome: '1 Timóteo', grupo: 'cartas-paulo', capitulos: 6, resumo: 'Manual pastoral para o jovem Timóteo: a ordem na igreja, o perfil dos líderes e o combate — "milita a boa milícia da fé".' },
  { nome: '2 Timóteo', grupo: 'cartas-paulo', capitulos: 4, resumo: 'O testamento de Paulo, escrito à espera da execução: "combati o bom combate" e a herança — "toda Escritura é divinamente inspirada".' },
  { nome: 'Tito', grupo: 'cartas-paulo', capitulos: 3, resumo: 'Instruções para organizar as igrejas de Creta: sã doutrina, boas obras e a graça de Deus "que traz salvação a todos os homens".' },
  { nome: 'Filemom', grupo: 'cartas-paulo', capitulos: 1, resumo: 'Um bilhete que mudou o mundo: Paulo intercede pelo escravo fugitivo Onésimo, agora irmão — o evangelho aplicado à reconciliação.' },
  { nome: 'Hebreus', grupo: 'cartas-gerais', capitulos: 13, resumo: 'Cristo é superior a tudo: anjos, Moisés, sacerdotes e sacrifícios. A galeria dos heróis da fé e o chamado a não retroceder.' },
  { nome: 'Tiago', grupo: 'cartas-gerais', capitulos: 5, resumo: 'A fé que funciona: provas, língua, riqueza e oração — "sede cumpridores da palavra e não somente ouvintes".' },
  { nome: '1 Pedro', grupo: 'cartas-gerais', capitulos: 5, resumo: 'Esperança viva para peregrinos em sofrimento: eleitos, provados pelo fogo e chamados a lançar toda a ansiedade sobre Aquele que cuida.' },
  { nome: '2 Pedro', grupo: 'cartas-gerais', capitulos: 3, resumo: 'A última carta de Pedro: crescer na graça, vigiar contra os falsos mestres e esperar "novos céus e nova terra, em que habita a justiça".' },
  { nome: '1 João', grupo: 'cartas-gerais', capitulos: 5, resumo: 'As certezas do cristão: Deus é luz, Deus é amor, e "quem tem o Filho tem a vida" — a carta da comunhão e da segurança da salvação.' },
  { nome: '2 João', grupo: 'cartas-gerais', capitulos: 1, resumo: 'Andar na verdade e no amor — e a advertência contra os enganadores que negam a vinda de Cristo em carne.' },
  { nome: '3 João', grupo: 'cartas-gerais', capitulos: 1, resumo: 'O contraste entre a hospitalidade de Gaio e a arrogância de Diótrefes: "não imites o mal, mas o bem".' },
  { nome: 'Judas', grupo: 'cartas-gerais', capitulos: 1, resumo: 'Um alerta urgente: batalhar pela fé entregue aos santos, resistir aos infiltrados e edificar-se "sobre a vossa santíssima fé".' },
  { nome: 'Apocalipse', grupo: 'profetico-nt', capitulos: 22, resumo: 'A revelação de Jesus Cristo: as cartas às sete igrejas, os juízos finais, a queda da Babilônia e o final glorioso — novo céu, nova terra e Deus habitando com os homens.' },
];

export const TOTAL_CAPITULOS = LIVROS.reduce((s, l) => s + l.capitulos, 0);
